// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXyZK0GeJQCnAPxnRRBIDj_oApi0qGq3w',
    appId: '1:938147966810:web:07caa3df41cd6a15fb4d63',
    messagingSenderId: '938147966810',
    projectId: 'weather-notification-186a7',
    authDomain: 'weather-notification-186a7.firebaseapp.com',
    storageBucket: 'weather-notification-186a7.appspot.com',
    measurementId: 'G-K8TGT4ZZC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLEuTpokRys2mhlpVno4QIH8eWU3UZDPQ',
    appId: '1:938147966810:android:1fa7f7e0b90f57d1fb4d63',
    messagingSenderId: '938147966810',
    projectId: 'weather-notification-186a7',
    storageBucket: 'weather-notification-186a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5xfsgoS19KlHAuRffZbl7fUREiVDF4oA',
    appId: '1:938147966810:ios:c4a95d98bab049f1fb4d63',
    messagingSenderId: '938147966810',
    projectId: 'weather-notification-186a7',
    storageBucket: 'weather-notification-186a7.appspot.com',
    iosBundleId: 'com.example.task5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5xfsgoS19KlHAuRffZbl7fUREiVDF4oA',
    appId: '1:938147966810:ios:18104ac596d1f73dfb4d63',
    messagingSenderId: '938147966810',
    projectId: 'weather-notification-186a7',
    storageBucket: 'weather-notification-186a7.appspot.com',
    iosBundleId: 'com.example.task5.RunnerTests',
  );
}
